In [79]:
import numpy as np
import random

In [80]:
def dot(a, b):
    """
    Dot product between two vectors 

    Args: 
        a: a n-dim vector (list, 1d np array, 1d tensor...)
        b: a n-dim vector (list, np array, tensor...)
    
    Returns: 
        c: Dot product of a and b (float)
    """
    total = 0
    for i in range(len(a)):
        total += a[i] * b[i]
    return total
    


def mm(A, B): 
    """
    Matrix multiply.

    Args: 
        A: n x m matrix (list of lists, np array, tensor...)
        B: m x p matrix (list of lists, np array, tensor...)

    Returns:
        C: A @ B 
    """
    # Your code here
    # Use the dot product function above to help you

    matrix = []

    n = len(A)
    m = len(A[0])
    p = len(B[0])

    for i in range(n):
        row_vec = []

        a = A[i]

        for x in range(p):
            b = []
            for j in range(m):
                b.append(B[j][x])
            row_vec.append(dot(a,b))
        matrix.append(row_vec)
    return matrix

def transpose(A): 
    """
    Transpose a matrix. (You will need this later.) 

    Args: 
        A: a n x m matrix A (list of lists, np array, tensor...)

    Returns:
        A^T: a m x n matrix, with rows and columns of A swapped.  
    """
    # Your code here
    n = len(A)
    m = len(A[0])

    matrix = []
    for i in range(m):
        col = []
        for j in range(n):
            col.append(A[j][i])
        matrix.append(col)
    return matrix


In [81]:
low_bound = 1
high_bound = 5 
# matrix_shape = (4, 4) 

A = [[4,5],[0,1],[2,2]]
B = [[3,4,1], [2,1,2]]

print("A: \n", A)
print("B: \n", B)



# print(A[0])

print("A @ B (my version): ", mm(A,B))

A = np.array([[4,5],[0,1],[2,2]])
B = np.array([[3,4,1], [2,1,2]])

print("A @ B: \n", A @ B)



A: 
 [[4, 5], [0, 1], [2, 2]]
B: 
 [[3, 4, 1], [2, 1, 2]]
A @ B (my version):  [[22, 21, 14], [2, 1, 2], [10, 10, 6]]
A @ B: 
 [[22 21 14]
 [ 2  1  2]
 [10 10  6]]


In [82]:
from math import exp

def compute_sigmoid(x):
    try:
        return [compute_sigmoid(y) for y in iter(x)]
    except:
        return 1 / (1 + exp(-x))

def sigmoid(x):
    """
    The sigmoid function. 

    Args: 
        x: a float, list of floats, list-of-lists of floats, np array, tensor. At most 2D.
    Returns: 
        sigmoid(x)
    """
    # Your code here
    return compute_sigmoid(x)

def copmute_relu(x):
    try:
        return [copmute_relu(y) for y in iter(x)]
    except:
        return max(0, x)

def relu(x):
    """
    The ReLU (rectified linear unit) function. 
    
    Args:
        x: a float, list of floats, list-of-lists of floats, np array, tensor. At most 2D.
    Returns: 
        ReLU(x)
    """
    # Your code here
    return copmute_relu(x)

In [83]:
class LinearLayer:
    """
    A mock fully-connected linear layer: 
    y = xW^T + b
    """
    def __init__(self, in_features, out_features, weight=None, bias=None):
        """
        Initialize a layer that accepts in_features in and outputs 
        out_features. If provided, initialize the weight matrix and bias vector
        with provided values. Otherwise, set all weights and bias to 0.0. 

        Args: 
            in_features: int
            out_features: int
            weight: Optional out_features x in_features matrix
                (list-of-lists). 
            bias: Optional bias vector of size out_features. 
        """
        self.in_features = in_features
        self.out_features = out_features

        # Your code here!
        if weight is not None: 
            self.weight = weight 
        else: 
            # initialize weight by setting it to 0
            self.weight = []
            for i in range(out_features):
                row = []
                for j in range(in_features):
                    row.append(0)
                self.weight.append(row)


        if bias is not None:
            self.bias = bias
        else:
            # initialize bias by setting it to 0
            self.bias = []
            for i in range(out_features):
                self.bias.append(0)
    
    def forward(self, x):
        """
        Args: 
            x: Input array-like with shape (*, self.in_features)
        
        Returns: 
            y: Output array-like with shape (*, self.out_features)
        """
        # Your code here!
        a = mm(x,transpose(self.weight))

        matrix = []
        for row in a:
            vec = []
            for i, b in zip(row, self.bias):
                vec.append(i+b)
            matrix.append(vec)
        return matrix


In [84]:
# REAL PYTROCH LINEAR MODEL FOR COMPARISION
import torch
import torch.nn as nn
import torch.nn.functional as F

class CustomLinearModel(nn.Module):
    def __init__(self, in_features, out_features):
        super(CustomLinearModel, self).__init__()
        # Manually create and register the weight and bias parameters
        self.weight = nn.Parameter(torch.randn(out_features, in_features))
        self.bias = nn.Parameter(torch.randn(out_features))

    def forward(self, input_tensor):
        # Use F.linear to apply the transformation
        output = F.linear(input_tensor, self.weight, self.bias)
        return output

# F.linear takes in (input, weight, bias=None)



# Testing:

# Dimensions
in_features = 3
out_features = 5
input_data = torch.randn(128, in_features)

weights = [
    [0.1, 0.2, 0.3],
    [0.4, 0.5, 0.6],
    [0.7, 0.8, 0.9],
    [1.0, 1.1, 1.2],
    [1.3, 1.4, 1.5]
]
bias = [0.1, 0.2, 0.3, 0.4, 0.5]

# 4. Initialize our model with random weights
model = LinearLayer(in_features, out_features, weights, bias)

# PyTorch model
real_model = CustomLinearModel(in_features, out_features)
with torch.no_grad():
    real_model.weight.copy_(torch.tensor(weights))
    real_model.bias.copy_(torch.tensor(bias))


output_data = model.forward(input_data)
real_output_data = real_model(input_data)

print("My Output First Row:", output_data[0])
print("PyTorch Output First Row:", real_output_data[0])

My Output First Row: [tensor(0.8249), tensor(1.7004), tensor(2.5758), tensor(3.4512), tensor(4.3267)]
PyTorch Output First Row: tensor([0.8249, 1.7004, 2.5758, 3.4512, 4.3267], grad_fn=<SelectBackward0>)


In [85]:
class MLP: 
    def __init__(self):
        """
        An MLP with layers and activation functions as described
        above. 
        """
        self.layer1 = LinearLayer(8,16)
        self.layer2 = LinearLayer(16,32)
        self.layer3 = LinearLayer(32,16)
        self.layer4 = LinearLayer(16,8)
    
    def forward(self, x):
        """
        Implements the forward pass of the MLP. 
        """
        # Pass x through the first layer, take that result and pass it through the first activation function, then pass that result into the second layer, and so on

        # relu() and sigmoid() are called on the output of each layer before passing the data to the next one
        a = relu(self.layer1.forward(x))
        b = relu(self.layer2.forward(a))
        c = relu(self.layer3.forward(b))
        return sigmoid(self.layer4.forward(c))